name: sanity Build
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:addToCart

      - name: Cypress Test Report
        if: always()  #Test pass or fail report added
        uses: actions/upload-artifact@v4
        with:
            name: Mocha awsome reporter
            path: cypress/reports/html